server:
    port: 8991
    session-timeout: -1
logging:
    level:
        root: INFO

spring:
    main:
        show-banner: false
    jpa:
        hibernate:
            ddl-auto: none
        generate-ddl: false

multipart:
    maxFileSize: 50MB
    maxRequestSize: 50MB

---
spring:
    profiles: development
    datasource:
        platform: h2
        url: jdbc:h2:tcp://localhost:9092/~/development
        username: sa
        password: sa

---
spring:
    profiles: test
    datasource:
        platform: h2

---
spring:
    profiles: production
    datasource:
        url: jdbc:oracle:thin:@localhost:1521:hawkw 
        username: store
        password: PstoreLace

logging:
    file: /tmp/ais-storeplaces.log
    level:
        root: WARN
