CREATE TABLE ADM_USER (	
USER_ID int(10) NOT NULL primary key, 
USER_TYPE_ID int(10) NOT NULL,
LOGIN VARCHAR(30) NOT NULL, 
PASSWORD VARCHAR(100) NOT NULL, 
IS_BLOCKED INT(1) NOT NULL, 
DISPLAYED_NAME VARCHAR(150) NOT NULL 
);